### ISSUE TITLE
Firefox no-content bug

### ISSUE THREAD

**Issue by runruh** [unshiftio/requests#6]
There is also a bug in firefox that will default content to an xmldocument if there is no content and no content type specified which will throw an exception when parsed. 

https://bugzilla.mozilla.org/show_bug.cgi?id=521301

This works for me to get around the problem, but can certainly be improved upon (line 86 of browser.js):

``` js
var chunk = data.documentElement 
? (!window.JSON ? '' : JSON.stringify(data)) 
: data.slice(requests.offset);
```

**Comment by 3rd-Eden** [comment]
I'll look at it tomorrow, (my time). And make sure it get fixed and published.

**Comment by 3rd-Eden** [comment]
Fixed in a down stream dependency ([loads](https://github.com/unshiftio/loads/commit/c7cc87af2e8746892c4566f15fb50ed012155bca)) and added regression tests to master branch and released a recompile browser client in the latest release.

Thanks again for reporting.
